name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # Auto-increment version (no tag)
      - name: Bump version
        id: bump
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      # Commit and push version bump
      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): bump to ${{ steps.bump.outputs.version }} [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Push skipped (branch protection may apply)"

      - name: Build package
        run: npm run build --if-present

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
